'use client';
import { useState } from 'react';

type Details = { ingredients:string; fruitContent:string; nutritionFat:string; nutritionSaturatedFat:string; nutritionCarbohydrates:string; nutritionSugars:string; nutritionProtein:string; nutritionSalt:string; nutritionEnergy:string; storageConditions:string; shelfLife:string; allergens:string; countryOfOrigin:string; manufacturer:string; importer:string; consumerClaims:string; isGmoFree:boolean };
type Product = { article:string; name:string; barcode:string|null };
const blank: Details = { ingredients:'',fruitContent:'',nutritionFat:'',nutritionSaturatedFat:'',nutritionCarbohydrates:'',nutritionSugars:'',nutritionProtein:'',nutritionSalt:'',nutritionEnergy:'',storageConditions:'',shelfLife:'',allergens:'',countryOfOrigin:'',manufacturer:'',importer:'',consumerClaims:'',isGmoFree:false };
const inputFields: Array<[keyof Details, string, boolean?]> = [['ingredients','Склад',true],['fruitContent','Вміст фруктів / примітка',true],['nutritionFat','Жири'],['nutritionSaturatedFat','Насичені жири'],['nutritionCarbohydrates','Вуглеводи'],['nutritionSugars','Цукри'],['nutritionProtein','Білок'],['nutritionSalt','Сіль'],['nutritionEnergy','Енергетична цінність'],['storageConditions','Зберігання',true],['shelfLife','Термін реалізації',true],['allergens','Алергени',true],['countryOfOrigin','Країна походження'],['manufacturer','Виробник',true],['importer','Імпортер в Україні',true],['consumerClaims','Претензії від споживачів',true]];
export default function AdminProductInfoManager() { const [code,setCode]=useState(''); const [product,setProduct]=useState<Product|null>(null); const [details,setDetails]=useState<Details>(blank); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
 async function load(){ setBusy(true); setMessage(''); try { const r=await fetch(`/api/admin/product-info?code=${encodeURIComponent(code)}`); const p=await r.json(); if(!r.ok||!p.ok) throw new Error(p.error); setProduct(p.product); setDetails(p.details); } catch(e){setProduct(null);setMessage(e instanceof Error?e.message:'Не вдалося знайти товар.')} finally{setBusy(false)} }
 async function save(){ if(!product)return; setBusy(true);setMessage(''); try { const r=await fetch('/api/admin/product-info',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,details})}); const p=await r.json();if(!r.ok||!p.ok)throw new Error(p.error);setCode('');setProduct(null);setDetails(blank);setMessage('Дані товару збережено.');}catch(e){setMessage(e instanceof Error?e.message:'Не вдалося зберегти дані.')}finally{setBusy(false)} }
 return <div><p className="text-xs font-semibold uppercase tracking-[.2em] text-brand">Admin / Контент</p><h1 className="mt-2 text-2xl font-bold text-slate-900 sm:text-3xl">Інформація про імпортні товари</h1><p className="mt-3 text-sm text-slate-700">Знайдіть товар за артикулом або штрихкодом, заповніть окремі поля та збережіть публічну картку.</p><div className="mt-6 flex max-w-xl gap-3"><input value={code} onChange={e=>setCode(e.target.value)} className="min-w-0 flex-1 rounded-xl border border-slate-300 px-4 py-3" placeholder="Артикул або штрихкод"/><button type="button" onClick={()=>void load()} disabled={busy} className="rounded-full bg-brand px-5 py-3 text-sm font-semibold text-white">Знайти</button></div>{message?<p className="mt-4 text-sm font-medium text-slate-700">{message}</p>:null}{product?<section className="mt-6 max-w-4xl rounded-2xl border border-slate-200 p-5"><h2 className="text-xl font-bold text-slate-900">{product.name}</h2><p className="mt-1 text-sm text-slate-600">Артикул: {product.article} · Штрихкод: {product.barcode ?? '—'}</p><div className="mt-6 grid gap-4 sm:grid-cols-2">{inputFields.map(([field,label,multiline])=><label key={field} className={multiline?'sm:col-span-2':''}><span className="text-sm font-medium text-slate-700">{label}</span>{multiline?<textarea value={String(details[field])} onChange={e=>setDetails({...details,[field]:e.target.value})} className="mt-1 min-h-24 w-full rounded-xl border border-slate-300 px-3 py-2"/>:<input value={String(details[field])} onChange={e=>setDetails({...details,[field]:e.target.value})} className="mt-1 w-full rounded-xl border border-slate-300 px-3 py-2"/>}</label>)}</div><label className="mt-4 flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={details.isGmoFree} onChange={e=>setDetails({...details,isGmoFree:e.target.checked})}/> Без ГМО</label><button type="button" onClick={()=>void save()} disabled={busy} className="mt-6 rounded-full bg-brand px-5 py-3 text-sm font-semibold text-white">Зберегти дані товару</button></section>:null}</div> }