'use client';

import { useEffect, useState } from 'react';

type Settings = { enabled: boolean; botToken: string; botUsername: string; webhookSecret: string; publicBaseUrl: string; allowedChatId: string };
const empty: Settings = { enabled: false, botToken: '', botUsername: '', webhookSecret: '', publicBaseUrl: '', allowedChatId: '' };

export default function FunTelegramManager() {
  const [settings, setSettings] = useState<Settings>(empty);
  const [webhookUrl, setWebhookUrl] = useState('');
  const [notice, setNotice] = useState('');
  const [busy, setBusy] = useState(false);
  useEffect(() => { void (async () => { const response = await fetch('/api/admin/fun-telegram', { cache: 'no-store' }); const data = await response.json(); if (response.ok) { setSettings(data.settings); setWebhookUrl(data.webhookUrl ?? ''); } else setNotice(data.error ?? 'Не вдалося завантажити налаштування.'); })(); }, []);
  function update(name: keyof Settings, value: string | boolean) { setSettings((current) => ({ ...current, [name]: value })); }
  async function save(): Promise<boolean> { setBusy(true); setNotice(''); try { const response = await fetch('/api/admin/fun-telegram', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ settings }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? 'Не вдалося зберегти.'); setSettings(data.settings); setWebhookUrl(data.webhookUrl ?? ''); setNotice('Налаштування збережено.'); return true; } catch (error) { setNotice(error instanceof Error ? error.message : 'Помилка збереження.'); return false; } finally { setBusy(false); } }
  async function registerWebhook() { if (!(await save())) return; setBusy(true); setNotice(''); try { const response = await fetch('/api/admin/fun-telegram', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'register-webhook' }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? 'Не вдалося зареєструвати webhook.'); setWebhookUrl(data.webhookUrl ?? ''); setNotice('Webhook зареєстровано. Тепер можна ввімкнути бота.'); } catch (error) { setNotice(error instanceof Error ? error.message : 'Помилка webhook.'); } finally { setBusy(false); } }
  const field = 'mt-1 w-full rounded-xl border border-slate-300 px-3 py-2 text-sm text-slate-900';
  return <div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-brand">Telegram</p><h1 className="mt-2 text-2xl font-bold text-slate-900">Тестовий бот жартів</h1><p className="mt-3 text-sm text-slate-700">Бот обробляє лише команди в одній тестовій групі. Він не читає та не зберігає звичайні повідомлення.</p><div className="mt-6 grid gap-4 rounded-2xl border border-slate-200 bg-slate-50 p-4 sm:grid-cols-2"><label className="text-sm font-medium text-slate-800 sm:col-span-2">Bot token<input className={field} type="password" value={settings.botToken} onChange={(e) => update('botToken', e.target.value)} autoComplete="off" /></label><label className="text-sm font-medium text-slate-800">Username бота<input className={field} value={settings.botUsername} onChange={(e) => update('botUsername', e.target.value)} placeholder="my_test_bot" /></label><label className="text-sm font-medium text-slate-800">ID тестової групи<input className={field} value={settings.allowedChatId} onChange={(e) => update('allowedChatId', e.target.value)} placeholder="-100..." /></label><label className="text-sm font-medium text-slate-800 sm:col-span-2">Публічна адреса сайту<input className={field} value={settings.publicBaseUrl} onChange={(e) => update('publicBaseUrl', e.target.value)} placeholder="https://pchilka-new.eatshock.com" /></label><label className="text-sm font-medium text-slate-800 sm:col-span-2">Webhook secret<input className={field} type="password" value={settings.webhookSecret} onChange={(e) => update('webhookSecret', e.target.value)} autoComplete="off" placeholder="мінімум 12 символів" /></label><label className="flex items-center gap-3 text-sm font-semibold text-slate-900 sm:col-span-2"><input type="checkbox" checked={settings.enabled} onChange={(e) => update('enabled', e.target.checked)} /> Увімкнути бота в тестовій групі</label></div><p className="mt-3 break-all text-xs text-slate-500">Webhook: {webhookUrl || 'вкажіть публічну адресу сайту'}</p><div className="mt-5 flex flex-wrap gap-3"><button disabled={busy} onClick={() => void save()} className="rounded-xl bg-brand px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">Зберегти</button><button disabled={busy} onClick={() => void registerWebhook()} className="rounded-xl border border-brand px-4 py-2 text-sm font-semibold text-brand disabled:opacity-60">Зареєструвати webhook</button></div>{notice ? <p className="mt-4 text-sm text-slate-700">{notice}</p> : null}<p className="mt-6 text-sm text-slate-600">Команди: <code>/start</code>, <code>/help</code>, <code>/joke</code>.</p></div>;
}
