import { NextResponse } from 'next/server';
import { isAdminRequestAuthorized, unauthorizedAdminResponse } from '@/lib/admin-auth';
import { buildCareerTelegramStartUrl, buildCareerTelegramWebhookUrl, isValidTelegramBotToken, isValidTelegramBotUsername, isValidTelegramChatId, isValidWebhookSecret, normalizeCareerTelegramSettings, type CareerTelegramSettings } from '@/lib/career-telegram-settings';
import { getCareerTelegramSettings, listCareerTelegramCities, saveCareerTelegramSettings } from '@/lib/career-telegram-settings-repository';
import { getCareerTelegramWebhookInfo, registerCareerTelegramWebhook } from '@/lib/career-telegram-bot';
export const runtime = 'nodejs';
export async function GET(request: Request) { if (!isAdminRequestAuthorized(request)) return unauthorizedAdminResponse(); const [settings, cities] = await Promise.all([getCareerTelegramSettings(), listCareerTelegramCities()]); const settingsWithStoreCities = { ...settings, cities: cities.length ? cities : settings.cities }; return NextResponse.json({ ok: true, settings: settingsWithStoreCities, webhookUrl: buildCareerTelegramWebhookUrl(settingsWithStoreCities), startUrl: buildCareerTelegramStartUrl(settingsWithStoreCities) }); }
export async function PUT(request: Request) {
  if (!isAdminRequestAuthorized(request)) return unauthorizedAdminResponse();
  try { const body = await request.json() as { settings?: Partial<CareerTelegramSettings> }; const settings = normalizeCareerTelegramSettings({ ...body.settings, updatedAt: new Date().toISOString() }); const invalid = [!isValidTelegramBotToken(settings.botToken) && 'Bot token', !isValidTelegramBotUsername(settings.botUsername) && 'Username бота', !isValidTelegramChatId(settings.hrChatId) && 'ID HR-чату', !isValidWebhookSecret(settings.webhookSecret) && 'Webhook secret'].filter(Boolean); if (invalid.length) return NextResponse.json({ ok: false, error: `Некоректні поля: ${invalid.join(', ')}.` }, { status: 400 }); const saved = await saveCareerTelegramSettings(settings); return NextResponse.json({ ok: true, settings: saved, webhookUrl: buildCareerTelegramWebhookUrl(saved), startUrl: buildCareerTelegramStartUrl(saved) }); }
  catch (error) { return NextResponse.json({ ok: false, error: error instanceof Error ? error.message : 'Unknown error' }, { status: 500 }); }
}
export async function POST(request: Request) { if (!isAdminRequestAuthorized(request)) return unauthorizedAdminResponse(); try { const action = (await request.json() as { action?: string }).action; if (action === 'register-webhook') return NextResponse.json({ ok: true, ...(await registerCareerTelegramWebhook()) }); if (action === 'check-webhook') return NextResponse.json({ ok: true, ...(await getCareerTelegramWebhookInfo()) }); return NextResponse.json({ ok: false, error: 'Unknown action.' }, { status: 400 }); } catch (error) { return NextResponse.json({ ok: false, error: error instanceof Error ? error.message : 'Unknown error' }, { status: 500 }); } }
